config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root 'pages#landing'
  get 'pages/about'
  get 'profiles/subscribes_list'
  get 'profiles/friends_photos'
  get 'profiles/my_photos'
  get 'profiles/:id' => 'profiles#show', as: 'profile'
  post 'profiles/:id/subscribe' => 'profiles#subscribe', as: 'subscribe'
  post 'profiles/:id/unsubscribe' => 'profiles#unsubscribe', as: 'unsubscribe'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment :image, presence: true
  validates :description, presence: true

  if Rails.env.development?
    has_attached_file :image,
    :path => ":rails_root/public/photos/system/:attachment/:id/:style/:filename",
    :url => "/photos/system/:attachment/:id/:style/:filename",
    styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :photos
  has_many :subscriptions
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def set_locale
    I18n.locale = extract_locale
  end

  private

  def extract_locale
    http_accept_language = request.env['HTTP_ACCEPT_LANGUAGE']
    if http_accept_language
      case http_accept_language.scan(/^[a-z]{2}/).first
      when 'en'
        'en'
      when 'ru'
        'ru'
      else
        'en'
      end
    else
      'en'
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    if user_signed_in?
      redirect_to photos_path
    end
  end

  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :owner?, only: [:edit, :update, :destroy]
  def index
    @photos = Photo.all.order(created_at: :desc).paginate(page: params[:page], per_page: 30)
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params.merge(user_id: current_user.id))
      if @photo.save
        redirect_to @photo, notice: 'Photo was successfully created.'
      else
        render :new
      end
  end

  def update
      if @photo.update(photo_params)
        redirect_to @photo, notice: 'Photo was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @photo.destroy
      redirect_to photos_url, notice: 'Photo was successfully destroyed.'
  end

  private

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:description, :image)
    end

    def owner?
      @photo = current_user.photos.find_by(id: params[:id])
      redirect_to photos_path, notice: "You do not have permission to edit this photo.." if @photo.nil?
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, except: [:my_photos, :subscribes_list, :friends_photos]

  def subscribe
    if current_user.subscriptions.find_by_friend_id(@profile.id).nil?
      @subscription = current_user.subscriptions.build
      @subscription.friend_id = @profile.id
      if @subscription.save
        redirect_to profile_path(@profile), notice: "Subscribed."
      end
    else
      redirect_to profile_path(@profile), notice: "You are already subscribed."
    end
  end

  def unsubscribe
    @subscription = current_user.subscriptions.find_by_friend_id(@profile.id)
    unless @subscription.nil?
      @subscription.destroy
      redirect_to profile_path(@profile), notice: "Unsubscribed."
      else
        redirect_to profile_path(@profile), notice: "You have not been subscribed."
    end
  end

  def show
  end

  def friends_photos
    @photos = Photo.where(user_id: current_user.subscriptions.pluck(:friend_id)).order(created_at: :desc).paginate(page: params[:page], per_page: 30)
  end

  def subscribes_list
    @subscribes = User.where(id: current_user.subscriptions.pluck(:friend_id))
  end

  def my_photos
    @photos = current_user.photos.order(created_at: :desc).paginate(page: params[:page], per_page: 30)
  end

  private

  def set_profile
    @profile = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_navigation.html.erb
<div class="container">

  <nav class="navbar navbar-expand-lg navbar-light ">
    <%=link_to 'Instaphoto', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%=link_to t('navigation.about'), pages_about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%=link_to t('navigation.feed'), profiles_friends_photos_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%=link_to t('navigation.my_photos'), profiles_my_photos_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('navigation.new_photo'), new_photo_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.username %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <%=link_to t('navigation.subscribes'), profiles_subscribes_list_path, class: "nav-link active destroy_session" %>
              <%=link_to t('navigation.profile'), edit_user_registration_path, class: "nav-link active destroy_session" %>
              <%=link_to t('navigation.exit'), destroy_user_session_path, class: "nav-link active destroy_session", method: :delete %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaphoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if user_signed_in? %>
    <div class="container-background2">
  <% else %>
    <div class="container-background">
  <% end %>
      <div class="container-fluid ">
          <%= render "layouts/navigation" %>

          <div class="container">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container google-font-2">

<h1><%=t('about.header')%></h1>

app/views/pages/landing.html.erb
<% unless user_signed_in?%>
<div class=" container jumbotron">
  <h1 class="display-4 google-font-2"><b><%= t('landing.header') %></b></h1>
  <p class="lead"><%= t('landing.description') %></p>
  <hr class="my-4">
  <p><%= t('landing.cursor') %></p>
  <%= link_to t('landing.login'), new_user_session_path, class: "btn btn-success" %>
  <%= link_to t('landing.sign_up'), new_user_registration_path, class: "btn btn-success" %>
</div>
<%end%>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div><br/>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div><br/>

  <div class="actions">
    <%= form.submit t('upload'), class: "btn btn-success" %>
  </div><br/>
<% end %>

app/views/photos/edit.html.erb
<div class="card mb-3" style="max-width: 18rem;">
  <div class="card-header"><%=t('edit_photo')%></div>
  <div class="card-body">

    <%= render 'form', photo: @photo %>

    <%= button_to t('show'), @photo, class: "btn btn-dark", method: :get %><br/>
    <%= button_to t('back'), photos_path, class: "btn btn-dark", method: :get %>

</div>

app/views/photos/index.html.erb
  
  <div class="card-columns">
    <% @photos.each do |photo| %>
    <div class="card photo-card">
      <div class="card-body">
        <%= link_to photo do %>
        <%= image_tag photo.image.url(:medium), class: "index-incard-image" %>
        <% end %><br/><br/>
        <%= photo.description %></div>
        <span class="invi"><%= link_to profile_path(photo.user_id) do%>
        <%= ion_icon "person"%><%=photo.user.username%><%end%>
        <% if photo.user == current_user %>
          | <%= link_to edit_photo_path(photo) do %>
          <%= ion_icon "edit"%><%=t('edit')%><%end%> |
          <%= link_to photo, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= ion_icon "trash-b"%><%=t('delete')%><%end%>
        <% end %></span>
    </div>
    <% end %>
  </div>
  <div class="container">
  <%= will_paginate @photos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>
  </div>

app/views/photos/new.html.erb
<div class="card mb-3" style="max-width: 18rem;">
  <div class="card-header"><%= t('navigation.new_photo')%></div>
  <div class="card-body">

    <%= render 'form', photo: @photo %>

    <%= button_to t('back'), photos_path, class: "btn btn-dark", method: :get %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="container show-container">
  <div class="card photo-card">
  <h3><%=link_to @photo.user.username, profile_path(@photo.user)%></h3>
    <div class="card-body">

      <%= image_tag @photo.image.url(:large) %>
      <p>
        <strong>Description:</strong>
        <%= @photo.description %>
      </p>
      <% if @photo.user == current_user %>
      <%= link_to t('edit'), edit_photo_path(@photo) %> |
      <%= link_to t('delete'), @photo, method: :delete, data: { confirm: "Are you sure?" } %> |
      <% end %>
      <%= link_to t('back'), photos_path %>
    </div>
  </div>
</div>

app/views/profiles/friends_photos.html.erb
<div class="card-columns">
      <% @photos.each do |photo| %>
      <div class="card photo-card">
        <div class="card-body">
          <%= link_to photo do %>
          <%= image_tag photo.image.url(:medium), class: "index-incard-image" %>
          <% end %> <br/><br/>
          <%= photo.description %></div><br/>
          <span class="invi"><%= link_to profile_path(photo.user_id) do%>
          <%= ion_icon "person"%><%=photo.user.username%><%end%></span>
      </div>
      <% end %>
    </div><br/>
<%= will_paginate @photos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>

app/views/profiles/my_photos.html.erb
<div class="card-columns">
      <% @photos.each do |photo| %>
      <div class="card photo-card">
        <div class="card-body">
          <%= link_to photo do %>
          <%= image_tag photo.image.url(:medium), class: "index-incard-image" %>
          <% end %> <br/><br/>
          <%= photo.description %></div><br/>
            <span class="invi"><%= link_to edit_photo_path(photo) do %>
            <%= ion_icon "edit"%><%= t('edit')%><%end%> |
            <%= link_to photo, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= ion_icon "trash-b"%><%= t('delete')%><%end%></span>
      </div>
      <% end %>
    </div><br/>
<%= will_paginate @photos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>

app/views/profiles/show.html.erb
<div class="container">
<%= button_to t('back'), photos_path, class: "btn btn-dark", method: :get %>
  <div style="text-align:center"><h3><%=@profile.username%></h3>
  <% if current_user.id != @profile.id%>
    <% if current_user.subscriptions.find_by_friend_id(@profile.id).nil?%>
    <%= button_to t('subscribe'), subscribe_path, class: "btn btn-success"%>
    <% else %>
    <%= button_to t('unsubscribe'), unsubscribe_path, class: "btn btn-dark"%>
    <% end %>
  <% end %>
  <br/>
  </div>
    <div class="card-columns">
      <% @profile.photos.each do |photo| %>
      <div class="card photo-card">
        <div class="card-body">
          <%= link_to photo do %>
          <%= image_tag photo.image.url(:medium), class: "index-incard-image" %>
          <% end %><br/><br/>
          <%= photo.description %></div><br/>
          <span class="invi"><% if photo.user == current_user %>
            <%= link_to edit_photo_path(photo) do %>
            <%= ion_icon "edit"%><%= t('edit')%><%end%> |
            <%= link_to photo, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= ion_icon "trash-b"%><%= t('delete')%><%end%></span>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/profiles/subscribes_list.html.erb
<div class="card-columns">
  <% @subscribes.each do |s|%>
    <div class="card photo-card">
      <div class="card-body">
        <%= link_to s.username, profile_path(s) %>
      </div>
    </div>
  <% end %>
</div>